### ISSUE TITLE
error on members service

### ISSUE THREAD

**Issue by jhagen1908** [cgi-uswest-chimpls/portalweb#8]
Get an error on members page (after clicking home icon) - error occurred trying to access endpoint...does not always happen.

**Comment by jhagen1908** [comment]
I was not able to recreate this morning.  Will keep this issue open and retest frequently to try to capture a log.

**Comment by jhagen1908** [comment]
I see this more commonly on provider details and messages, including today.  I suspect this has to do with the templates not being compiled and requires a callback to the main loadProvider function after templates are done compiling.

Need to check with Evelina about whether she clicked on the house right away on load, or if she did other stuff first.

**Comment by jhagen1908** [comment]
May also relate to database conflicts given the low number of concurrent user connections on the databases.

**Comment by jhagen1908** [comment]
I recreated today.  Appears to be an issue where the controller is trying to communicate with the person service to get person details on the home member:

2018-08-17T05:59:37.831-05:00 [RTR/6] [OUT] portalweb.cfapps.io - [2018-08-17T10:59:34.476+0000] "GET /membersByProvider/7000000 HTTP/1.1" 500 0 195 "https://portalweb.cfapps.io/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36" "10.10.66.194:31652" "10.10.149.198:61148" x_forwarded_for:"161.69.123.14, 10.10.66.194" x_forwarded_proto:"https" vcap_request_id:"b1822cae-9ddb-4b21-52d7-ad87ddcf39a4" response_time:3.354885315 app_id:"80d2e394-ae76-4b26-9947-c0ccfe3717c7" app_index:"0" x_b3_traceid:"2778b0271c1a9495" x_b3_spanid:"2778b0271c1a9495" x_b3_parentspanid:"-"
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320) [spring-security-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) [spring-security-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) [spring-security-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) [spring-security-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) [spring-security-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137) [spring-security-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111) [spring-security-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170) [spring-security-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200) [spring-security-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) [spring-security-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66) [spring-security-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) [spring-security-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) [spring-security-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) [spring-security-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) [spring-security-web-5.0.5.RELEASE.jar!/:5.0.5.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357) [spring-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270) [spring-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilter.java:60) [spring-security-oauth2-2.3.2.RELEASE.jar!/:na]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) [spring-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) [spring-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-08-17T05:59:40.699-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) [spring-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.cloudfoundry.router.ClientCertificateMapper.doFilter(ClientCertificateMapper.java:77) [client_certificate_mapper-1.8.0_RELEASE.jar!/:1.8.0.RELEASE]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.31.jar!/:8.5.31]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] Caused by: java.net.SocketTimeoutException: Read timed out
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983) ~[na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940) ~[na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735) ~[na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) ~[na:1.8.0_181]
2018-08-17T05:59:40.700-05:00 [APP/PROC/WEB/0] [OUT] at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587) ~[na:1.8.0_181]
2018-08-17T05:59:40.701-05:00 [APP/PROC/WEB/0] [OUT] at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:94) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.701-05:00 [APP/PROC/WEB/0] [OUT] at rx.internal.operators.OnSubscribeConcatMap.call(OnSubscribeConcatMap.java:42) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.701-05:00 [APP/PROC/WEB/0] [OUT] at rx.Observable.unsafeSubscribe(Observable.java:10151) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.701-05:00 [APP/PROC/WEB/0] [OUT] at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1.call(OperatorRetryWithPredicate.java:127) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.701-05:00 [APP/PROC/WEB/0] [OUT] at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.enqueue(TrampolineScheduler.java:73) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.701-05:00 [APP/PROC/WEB/0] [OUT] at rx.internal.schedulers.TrampolineScheduler$InnerCurrentThreadScheduler.schedule(TrampolineScheduler.java:52) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.701-05:00 [APP/PROC/WEB/0] [OUT] at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:79) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.701-05:00 [APP/PROC/WEB/0] [OUT] at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber.onNext(OperatorRetryWithPredicate.java:45) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.701-05:00 [APP/PROC/WEB/0] [OUT] at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.701-05:00 [APP/PROC/WEB/0] [OUT] at rx.Subscriber.setProducer(Subscriber.java:209) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.701-05:00 [APP/PROC/WEB/0] [OUT] at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.701-05:00 [APP/PROC/WEB/0] [OUT] at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.702-05:00 [APP/PROC/WEB/0] [OUT] at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.702-05:00 [APP/PROC/WEB/0] [OUT] at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.702-05:00 [APP/PROC/WEB/0] [OUT] at rx.Observable.subscribe(Observable.java:10247) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.702-05:00 [APP/PROC/WEB/0] [OUT] at rx.Observable.subscribe(Observable.java:10214) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.702-05:00 [APP/PROC/WEB/0] [OUT] at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.702-05:00 [APP/PROC/WEB/0] [OUT] at rx.observables.BlockingObservable.single(BlockingObservable.java:341) ~[rxjava-1.2.0.jar!/:1.2.0]
2018-08-17T05:59:40.702-05:00 [APP/PROC/WEB/0] [OUT] at com.netflix.client.AbstractLoadBalancerAwareClient.executeWithLoadBalancer(AbstractLoadBalancerAwareClient.java:112) ~[ribbon-loadbalancer-2.2.5.jar!/:2.2.5]
2018-08-17T05:59:40.702-05:00 [APP/PROC/WEB/0] [OUT] at org.springframework.cloud.openfeign.ribbon.LoadBalancerFeignClient.execute(LoadBalancerFeignClient.java:63) ~[spring-cloud-openfeign-core-2.0.0.RC2.jar!/:2.0.0.RC2]
2018-08-17T05:59:40.702-05:00 [APP/PROC/WEB/0] [OUT] at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97) ~[feign-core-9.5.1.jar!/:na]
2018-08-17T05:59:40.702-05:00 [APP/PROC/WEB/0] [OUT] at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76) ~[feign-core-9.5.1.jar!/:na]
2018-08-17T05:59:40.702-05:00 [APP/PROC/WEB/0] [OUT] at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103) ~[feign-core-9.5.1.jar!/:na]
2018-08-17T05:59:40.702-05:00 [APP/PROC/WEB/0] [OUT] at com.sun.proxy.$Proxy171.getPersonDataByIdprsn(Unknown Source) ~[na:na]
2018-08-17T05:59:40.702-05:00 [APP/PROC/WEB/0] [OUT] at com.cgi.uswest.chimpls.portalweb.controller.PortalwebApplicationController.findMembersByProvider(PortalwebApplicationController.java:400) ~[classes/:na]

**Comment by jhagen1908** [comment]
Increased Ribbon timeouts to 20 seconds from the default 1 second via commit c50fcab on the configuration server.

https://github.com/cgi-uswest-chimpls/cw-portal-config-repo/commit/c50fcabd9fabf74e7234934f49e7bc8eae4d731e

Tested repeatedly with Bucky and Portal User, and I have not been able to recreate any of the following service errors I had seen repeatedly in the past:

Error on providerDetail (startup)
Error on messages (startup)
Error on members (modal launch)

I believe this issue is resolved.  If the errors recur we can reopen.
